name = "worker-yalim"
main = "src/index.ts"
compatibility_date = "2024-10-22"
workers_dev = true

[vars]
BASE_URL = "http://127.0.0.1:8787"

# Override values for `--env production` usage
[env.production]
routes = [
	{ pattern = "yalim.sh", custom_domain = true }
]

[env.production.vars]
BASE_URL = "https://yalim.sh"